# Generated by Django 5.1.7 on 2025-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointmentconfig_max_daily_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentconfig',
            name='max_daily_appointments',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
